### ISSUE TITLE
capistrano-runit-sidekiq won't run runit:sidekiq:setup

### ISSUE THREAD

**Issue by jancel** [capistrano-runit/sidekiq#3]
Successful steps (Debian Wheezy)
sudo apt-get install runit
Set up capistrano-runit-core with my environment specific options
Add capistrano-runit-core
cap production runit:setup

I've added capistrano-runit-core and followed the setup instructions for that. All works well. Then I've added capistrano-runit-sidekiq and it complains.  I want to install sidekiq only for now.  First complaint I saw was a folder was missing, I just created the folder to move forward. Now I get this:

```
DEBUG [702dcf8e] Command: [ ! -d /home/deployment/rokkit-rails/runit/available/sidekiq ]
DEBUG [702dcf8e] Finished in 0.079 seconds with exit status 1 (failed).
ERROR Template from 'runit_sidekiq_run_template' variable isn't found:
```

EDIT (adding details that aren't quite clear to me):

Only thing I see on the home page/readme for this is this line, which makes little sense, since I'm not attempting puma right now.

```
runit_sidekiq_run_template -- path to ERB template of run file. Default value: internal default template (lib/capistrano/runit/templates/run-puma.erb).
```

Is a dependency Puma for this gem to work?

**Comment by antage** [comment]
@jancel `runit_sidekiq_run_template` variable was deprecated and `capistrano-runit-sidekiq` doesn't use it anymore. Try to update gem from github (`gem 'capistrano-runit-sidekiq', github: 'capistrano-runit/sidekiq'` in `Gemfile` and run `bundle update capistrano-runit-sidekiq`).

> Is a dependency Puma for this gem to work?

No, it's copy-paste text from `capistrano-runit-puma`'s readme file. I fixed it.

**Comment by antage** [comment]
@jancel I advice to use github version for all capistrano-runit-* gems (`capistrano-runit-core` too).

**Comment by jancel** [comment]
@antage Thanks. I've updated the two, and will atempt this again in a few. I'll update the ticket once I know what's up.

**Comment by jancel** [comment]
@antage Okay. this definitely got past this issue, but something's still wonky. I'll open a new issue.
